# Generated by Django 3.0.5 on 2020-05-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('specialty', models.CharField(max_length=30)),
                ('students_number', models.PositiveIntegerField(default=13, null=True)),
            ],
        ),
    ]
