# Generated by Django 3.0.5 on 2020-05-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='students_number',
            field=models.PositiveIntegerField(default=25, null=True),
        ),
    ]
