# Generated by Django 3.0.5 on 2020-05-12 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20200508_1803'),
        ('group', '0002_auto_20200508_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='specialty',
        ),
        migrations.AddField(
            model_name='group',
            name='course',
            field=models.CharField(default='IT 200: Web Phishing', max_length=60),
        ),
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.Teacher'),
        ),
    ]
