# Generated by Django 3.0.5 on 2020-05-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_auto_20200512_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='course',
            field=models.CharField(default='IT 200: Web Phishing.', max_length=60),
        ),
    ]
