# Generated by Django 3.0.5 on 2020-05-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20200504_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='telephone',
            field=models.CharField(default=380677777777, max_length=20, unique=True),
        ),
    ]
