# Generated by Django 3.0.5 on 2020-05-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=20, null=True)),
                ('telephone', models.CharField(max_length=15)),
                ('github_repository', models.URLField(max_length=100, null=True)),
                ('experience', models.PositiveIntegerField(default=2)),
            ],
        ),
    ]
