# Generated by Django 3.0.5 on 2020-05-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20200508_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='telephone',
            field=models.CharField(default=None, max_length=20, null=True, unique=True),
        ),
    ]
